### ISSUE TITLE
\NewPitonLanguage

### ISSUE THREAD

**Issue by zariski63** [fpantigny/piton#2]
Bonjour, il semblerait que la commande `\NewPitonLanguage` ne fonctionne pas, tout du moins chez moi...
Pourtant je tape l'exemple à l'identique.
Voici l'erreur indiquée 

(c:/texlive/2024/texmf-dist/tex/lualatex/luacode/luacode.sty))[\directlua]:1: attempt to call a nil value (field 'new_language')
stack traceback:
 [\directlua]:1: in main chunk.
\lua_now:e #1->\__lua_now:n {#1}
 l.270 }

**Comment by fpantigny** [comment]
You devriez m'envoyer un mail avec le fichier exact que vous avez essayé de compiler (vous trouverez mon adresse sur la documentation de l'extension `piton`).

**Comment by zariski63** [comment]
Ok merci

**Comment by fpantigny** [comment]
Solved.

**Comment by manuelbb-upb** [comment]
Hi @fpantigny, thanks for the great package.
I am hitting the same issue unfortunately. I have tried version 3.0b and current main branch.
Is there a resolution?

**Comment by fpantigny** [comment]
Hi @manuelbb-upb : Send me a mail. You will find my address on the documentation of the package `piton`.

**Comment by manuelbb-upb** [comment]
Hi, thank you. I managed to fix the issue by changing `begindocument` to `begindocument / end` in [this line](https://github.com/fpantigny/piton/blob/18663770b27c9ea0440376d245b36c2612bdd462/piton.dtx#L4099).

**Comment by fpantigny** [comment]
Right, but I would be interested in a minimal example of the problem with the corresponding `log` file to see the versions of the different packages used. Then, I will be able to see whether I should insert your patch in a new version of `piton`.
