### ISSUE TITLE
Ability to change "main" color

### ISSUE THREAD

**Issue by nplatis** [fpantigny/piton#4]
I would like to be able to change the "main" color of code typeset with `piton`, to something else than the default black.

Doing so for the `Piton` environment is rather easy, by defining a `\NewPitonEnvironment` which starts with a `\color{}` command. But, of course, this does not affect the `\piton` command.

So, maybe adding a "Default" key to `\SetPitonStyle` would be a solution.

**Comment by fpantigny** [comment]
I have added a key `font-command`. Of course, it will be in the next version of `piton` on CTAN.

For that key, it's possible to write, for example: `\PitonOptions{font-command = \ttfamily \color{blue}}`
