### ISSUE TITLE
Indentation is lost when copying

### ISSUE THREAD

**Issue by alcrene** [fpantigny/piton#6]
If I open the current PDF `piton-french.pdf`, copy the first example and paste it into a text editor, the indentation is lost:

    def arctan(x,n=10:int):
    """Calcule la valeur mathématique de arctan(x)
    n est le nombre de termes de la somme
    """
    if x < 0:
    return -arctan(-x) # appel récursif
    elif x > 1:
    return pi/2 - arctan(1/x)
    (on a utilisé le fait que arctan(x) + arctan(1/x) = π/2 pour x > 0) 2
    else:
    s = 0
    for k in range(n):
    s += (-1)**k/(2*k+1)*x**(2*k+1)
    return s

This is obviously not ideal if someone wants to reuse code snippets.

**Comment by fpantigny** [comment]
That's a problem of the PDF format and, as far I know, there is no real solution, whatever tool you use to create a PDF with informatic listings...

**Comment by alcrene** [comment]
I was after afraid that would be the case. Thanks for confirming.
